--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JackMD/Charm
branches:
- master
projects:
  Charm:
    icon: meta/Charm.png
    libs:
    - src: JackMD/UpdateNotifier/UpdateNotifier
      version: ^1.0.0
    - src: JackMD/ConfigUpdater/ConfigUpdater
      version: ^1.0.0
...
