name: Charm
main: JackMD\Charm\Charm
author: JackMD
api: [3.0.0]
version: 1.0.0

permissions:
  charm:
    default: false
    description: Access to all charm commands and features.
    children:
      charm.command:
        default: false
        description: Access to all charm commands.
        children:
          charm.command.gamemode:
            default: false
            description: Allows using /gamemode command.
            children:
              charm.command.gamemode.use:
                default: op
              charm.command.gamemode.self:
                default: op
                description: Allows sender to change their gamemode.
              charm.command.gamemode.target:
                default: op
                description: Allows sender to change another players gamemode.

          charm.command.teleportall:
            default: false
            description: Allows using /tpall
            children:
              charm.command.teleportall.use:
                default: op
                description: Allows using /tpall

          charm.command.teleporthere:
            default: false
            description: Allows using /tphere
            children:
              charm.command.teleporthere.use:
                default: op
                description: Allows using /tphere